const menuItems = [
  {
    id: 1,
    name: "Margherita Pizza",
    category: "Pizza",
    price: 8.99,
    image: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg",
    rating: 4.5,
    description: "Classic pizza with tomato sauce, mozzarella, and basil.",
    quantity: 0,
  },
  {
    id: 2,
    name: "Cheeseburger",
    category: "Burger",
    price: 6.99,
    image: "https://images.pexels.com/photos/1128678/pexels-photo-1128678.jpeg",
    rating: 4.2,
    description: "Juicy beef patty with melted cheese, lettuce, and tomato.",
    quantity: 0,
  },
  {
    id: 3,
    name: "Spaghetti Carbonara",
    category: "Pasta",
    price: 9.99,
    image: "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg",
    rating: 4.7,
    description: "Creamy pasta with pancetta, egg, and Parmesan cheese.",
    quantity: 0,
  },
  {
    id: 4,
    name: "Caesar Salad",
    category: "Salad",
    price: 5.99,
    image: "https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg",
    rating: 4.3,
    description: "Crisp romaine lettuce, croutons, and Caesar dressing.",
    quantity: 0,
  },
  {
    id: 5,
    name: "Tandoori Chicken",
    category: "Indian",
    price: 12.99,
    image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
    rating: 4.8,
    description: "Spiced, grilled chicken with a tangy yogurt marinade.",
    quantity: 0,
  },
  {
    id: 6,
    name: "Sushi Platter",
    category: "Japanese",
    price: 18.99,
    image: "https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg",
    rating: 4.9,
    description: "Assorted sushi rolls and sashimi.",
    quantity: 0,
  },
  {
    id: 7,
    name: "French Fries",
    category: "Snacks",
    price: 3.49,
    image: "https://images.pexels.com/photos/1639563/pexels-photo-1639563.jpeg",
    rating: 4.1,
    description: "Crispy golden fries served with ketchup.",
    quantity: 0,
  },
  {
    id: 8,
    name: "Veggie Wrap",
    category: "Wraps",
    price: 7.49,
    image: "https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg",
    rating: 4.4,
    description: "Whole wheat wrap filled with fresh veggies and hummus.",
    quantity: 0,
  },
  {
    id: 9,
    name: "Chocolate Brownie",
    category: "Dessert",
    price: 4.99,
    image: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg",
    rating: 4.6,
    description: "Rich chocolate brownie topped with fudge.",
    quantity: 0,
  },
  {
    id: 10,
    name: "Chicken Biryani",
    category: "Indian",
    price: 10.99,
    image: "https://images.pexels.com/photos/461430/pexels-photo-461430.jpeg",
    rating: 4.8,
    description: "Fragrant basmati rice cooked with chicken and spices.",
    quantity: 0,
  },
];

export default menuItems;
